{
 "title": "BT Home Hub Statistics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "firmware",
    "label": "firmware",
    "query": "label_values(bt_homehub_build_info, firmware)"
   }
  ]
 },
 "panels": [
  {
   "title": "Download Speed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "bt_homehub_download_rate_mbps/1024"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Days" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "bt_homehub_uptime_seconds/60/60/24",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Upload Speed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "bt_homehub_upload_rate_mbps/1024"
    }
   ]
  },
  {
   "title": "Bandwidth Use Summary",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(bt_homehub_download_bytes_total[5m])",
     "legendFormat": "Downloads"
    },
    {
     "expr": "rate(bt_homehub_upload_bytes_total[5m])",
     "legendFormat": "Uploads"
    }
   ]
  },
  {
   "title": "Device Download Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(bt_homehub_device_downloaded_megabytes[$__rate_interval])",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Device Upload Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(bt_homehub_device_uploaded_megabytes[$__rate_interval])  ",
     "legendFormat": "{{host_name}}"
    }
   ]
  }
 ]
}